fix(actions): switch to the official setup-homebrew action
This change will convert our workflow to use the official setup-homebrew GitHub Action. This official action will handle our need to setup the git repository and ensure that the dependencies are up to date.

Also, this should resolve our issue with brew test-bot using a non-existing commit ID.

==> Running FormulaeDetect#detect_formulae!
==> git -C /opt/homebrew/Library/Taps/fidelity/homebrew-tap fetch origin +refs/heads/master
Error: Failure while executing; `/usr/bin/git -C /opt/homebrew/Library/Taps/fidelity/homebrew-tap merge-base 00fe35b6825162ac4bc9602e0dd8b9c0106526bb 759361d7fb2debb2970ac1eab98758960f59538d` exited with 128. Here's the output:

https://github.com/fidelity/homebrew-tap/commit/759361d7fb2debb2970ac1eab98758960f59538d

Signed-off-by: Casale, Robert <robert.casale@fmr.com>